### ISSUE TITLE
problem with installing

### ISSUE THREAD

**Issue by kazemimorteza68** [morilog/jalali#79]
Hi.
when i want install package using composer i have below error.
```
zsh: no matches found: morilog/jalali:3.*

```
Please help me.Thanks

**Comment by morilog** [comment]
How do you install?

**Comment by WiGeeky** [comment]
I don't know if the problem is specific to Zsh or not, but I've got the same error. To fix the issue, either specify the version (like below) 
`composer require morilog/jalali:3.1.1`
or let composer get the latest version:
`composer require morilog/jalali`
or get the latest version from GitHub (not always recommended):
`composer require morilog/jalali:dev-master`
